### ISSUE TITLE
いいね順でソートできるように検討する

### ISSUE THREAD

**Issue by s-nakajima** [NetCommons3/Likes#5]
件数の集計テーブルを持たせた方が良い？

**Comment by akagane99** [comment]
対応しない。という認識でオッケー？

**Comment by s-nakajima** [comment]
ソート機能を付けるかは、プラグインの使用によるので、
Likeプラグンとしては、集計テーブルを持たせたって意味でCloseした。

**Comment by akagane99** [comment]
なるほど、認識あらためます。
理解しました。
